name: Upgrade Sandwich
on:
  workflow_dispatch:
    inputs:
      sandwich_version:
        description: 'Sandwich version'
        required: true
        default: '0.0.0'

jobs:
  upgrade_sandwich:
    runs-on: ubuntu-latest
    env:
      sandwich_version: ${{ github.event.inputs.sandwich_version }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Bump version
        run: |
          fastlane upgrade_sandwich version:$sandwich_version

#      - name: Create pull request
#        uses: peter-evans/create-pull-request@v3
#        with:
#          title: Sandwich upgrade to ${{ env.sandwich_version }}
#          body: Sandwich upgrade to ${{ env.sandwich_version }}
#          labels: autocreated
#          branch: tech/sandwich_${{ env.sandwich_version }}
#          base: develop

      - name: Create release pull requests
        uses: qonversion/shared-sdk-workflows/.github/workflows/test.yml@main